services:
    _defaults:
        public: true

    threebrs.gopay_payum.gateway_factory:
        class: ThreeBRS\SyliusGoPayPayumPlugin\Payum\GoPayPaymentGatewayFactory

    threebrs.gopay_payum.gateway_factory_builder:
        class: Payum\Core\Bridge\Symfony\Builder\GatewayFactoryBuilder
        arguments:
            - '@threebrs.gopay_payum.gateway_factory'
        tags:
            - { name: 'payum.gateway_factory_builder', factory: 'gopay' }

    threebrs.gopay_payum.api:
        class: ThreeBRS\SyliusGoPayPayumPlugin\Api\GoPayApi
        arguments:
            $gopayPaymentsFactory: '@threebrs.gopay_payum.payments.factory'

    ThreeBRS\SyliusGoPayPayumPlugin\Api\GoPayApiInterface:
        alias: threebrs.gopay_payum.api

    threebrs.gopay_payum.form.type.gateway_configuration:
        class: ThreeBRS\SyliusGoPayPayumPlugin\Form\Type\GoPayPayumGatewayConfigurationType
        tags:
            - { name: 'sylius.gateway_configuration_type', type: 'gopay', label: 'threebrs.gopay_payum_plugin.gateway_label' }
            - { name: 'form.type' }

    threebrs.gopay_payum.action.capture:
        class: ThreeBRS\SyliusGoPayPayumPlugin\Payum\Action\CaptureAction
        tags:
            - { name: 'payum.action', factory: 'gopay' }

    threebrs.gopay_payum.action.convert_payment:
        class: ThreeBRS\SyliusGoPayPayumPlugin\Payum\Action\ConvertPaymentAction
        tags:
            - { name: 'payum.action', factory: 'gopay' }

    threebrs.gopay_payum.action.gopay:
        class: ThreeBRS\SyliusGoPayPayumPlugin\Payum\Action\GoPayAction
        arguments:
            - '@threebrs.gopay_payum.api'
            - '@payum'
        tags:
            - { name: 'payum.action', factory: 'gopay' }

    threebrs.gopay_payum.action.notify:
        class: ThreeBRS\SyliusGoPayPayumPlugin\Payum\Action\NotifyAction
        arguments:
            - '@threebrs.gopay_payum.api'
        tags:
            - { name: 'payum.action', factory: 'gopay' }

    threebrs.gopay_payum.action.refund:
        class: ThreeBRS\SyliusGoPayPayumPlugin\Payum\Action\RefundAction
        arguments:
            - '@threebrs.gopay_payum.api'
        tags:
            - { name: 'payum.action', factory: 'gopay' }

    threebrs.gopay_payum.action.cancel:
        class: ThreeBRS\SyliusGoPayPayumPlugin\Payum\Action\CancelAction
        arguments:
            - '@threebrs.gopay_payum.api'
        tags:
            - { name: 'payum.action', factory: 'gopay' }

    threebrs.gopay_payum.action.status:
        class: ThreeBRS\SyliusGoPayPayumPlugin\Payum\Action\StatusAction
        tags:
            - { name: 'payum.action', factory: 'gopay' }

    threebrs.gopay_payum.state_machine.refund:
        class: ThreeBRS\SyliusGoPayPayumPlugin\StateMachine\RefundOrderProcessor
        arguments:
            $commandBus: '@sylius.command_bus'

    threebrs.gopay_payum.state_machine.cancel:
        class: ThreeBRS\SyliusGoPayPayumPlugin\StateMachine\CancelOrderProcessor
        arguments:
            $commandBus: '@sylius.command_bus'

    threebrs.gopay_payum.command.handler.refund:
        public: true
        class: ThreeBRS\SyliusGoPayPayumPlugin\Message\CommandHandler\RefundPaymentHandler
        arguments:
            $refundRequestFactory: '@threebrs.gopay_payum.request.factory.refund'
            $captureRequestFactory: '@threebrs.gopay_payum.request.factory.capture'
            $payum: '@payum'
            $paymentRepository: '@sylius.repository.payment'
            $supportedGateways: [ 'gopay' ]
        tags:
            -   name: messenger.message_handler
                bus: sylius.command_bus

    threebrs.gopay_payum.command.handler.cancel:
        public: true
        class: ThreeBRS\SyliusGoPayPayumPlugin\Message\CommandHandler\CancelPaymentHandler
        arguments:
            $cancelRequestFactory: '@threebrs.gopay_payum.request.factory.cancel'
            $payum: '@payum'
            $paymentRepository: '@sylius.repository.payment'
            $logger: '@logger'
            $supportedGateways: [ 'gopay' ]
        tags:
            -   name: messenger.message_handler
                bus: sylius.command_bus

    threebrs.gopay_payum.request.factory.capture:
        class: ThreeBRS\SyliusGoPayPayumPlugin\Payum\Request\Factory\CaptureRequestFactory

    ThreeBRS\SyliusGoPayPayumPlugin\Payum\Request\Factory\CaptureRequestFactoryInterface:
        alias: threebrs.gopay_payum.request.factory.capture

    threebrs.gopay_payum.request.factory.refund:
        class: ThreeBRS\SyliusGoPayPayumPlugin\Payum\Request\Factory\RefundRequestFactory

    ThreeBRS\SyliusGoPayPayumPlugin\Payum\Request\Factory\RefundRequestFactoryInterface:
        alias: threebrs.gopay_payum.request.factory.refund

    threebrs.gopay_payum.request.factory.cancel:
        class: ThreeBRS\SyliusGoPayPayumPlugin\Payum\Request\Factory\CancelRequestFactory

    ThreeBRS\SyliusGoPayPayumPlugin\Payum\Request\Factory\CancelRequestFactoryInterface:
        alias: threebrs.gopay_payum.request.factory.cancel

    threebrs.gopay_payum.payments.factory:
        class: ThreeBRS\SyliusGoPayPayumPlugin\Payum\GoPayPaymentsFactory

    ThreeBRS\SyliusGoPayPayumPlugin\Payum\GoPayPaymentsFactoryInterface:
        alias: threebrs.gopay_payum.payments.factory
