#winzou_state_machine:
#    sylius_payment:
#        callbacks:
#            after:
#                threebrs.sylius_gopay_payum.refund:
#                    on: [ "refund" ]
#                    do: [ "@threebrs.gopay_payum.state_machine.refund", "__invoke" ]
#                    args: [ "object", "event.getState()" ]
#                threebrs.sylius_gopay_payum.cancel:
#                    on: [ "cancel" ]
#                    do: [ "@threebrs.gopay_payum.state_machine.cancel", "__invoke" ]
#                    args: [ "object", "event.getState()" ]
